# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7e0b805720cd86de8e030216d6d5ef55ed9f40a91b54524dda1dc31eed3d6d148883a757020dea5cbf85ab832a4539e7e580ca1f8ef96999c72224c410c1d67

test:
  secret_key_base: d1dc51bfe68ae63bd90b2708720179b9af14dc2fe23ce73a81572edd8f6e79104b3f10ea163cf29223f13917a1e4c9dd6a97828dd51e7aced1c4230e00dbfedf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
